/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devispro;

import static devispro.Conexion.getConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jefferson Medina
 */
public class Materiales extends javax.swing.JFrame {
    DefaultListModel material = new DefaultListModel();
    /**
     * Creates new form Materiales
     */
    public Materiales() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_añadir = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_quitar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbmateriales = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbaddmateriales = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("LISTA DE MATERIALES");

        btn_añadir.setText("AÑADIR");
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });

        btn_agregar.setText(">");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        btn_quitar.setText("<");
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });

        jLabel2.setText("BUSCAR :");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        jtbmateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod", "nombre", "unidad", "precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtbmateriales);

        jtbaddmateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRIPCION", "UNIDAD", "CANTIDAD(A)", "P.UNITARIO (B)", "COSTO (C=A*B)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtbaddmateriales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_añadir)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_agregar)
                                            .addComponent(btn_quitar))
                                        .addGap(24, 24, 24)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(btn_agregar)
                            .addGap(38, 38, 38)
                            .addComponent(btn_quitar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_añadir)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void nueva_tabla(){
    material = new DefaultListModel();
    String[] equipos= {"DESCRIPCION", "UNIDAD", "CANTIDAD(A)", "P.UNITARIO (B)", "COSTO (C=A*B)"};
        DefaultTableModel m = new DefaultTableModel(null, equipos);
        jtbaddmateriales.setModel(m);                
}
    
    private void mostrar(){
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = Conexion.getTable("select * from materiales");
        modelo.setColumnIdentifiers(new Object[]{"cod","nombre","unidad","precio"});
        try {
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("cod"),rs.getString("nombre"),rs.getString("unidad"),rs.getDouble("Precio")});
            }
            jtbmateriales.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<jtbaddmateriales.getRowCount(); i++){
            String vector[] = new String[5];
            vector[0]=jtbaddmateriales.getValueAt(i, 0).toString();
            vector[1]=jtbaddmateriales.getValueAt(i, 1).toString();
            vector[2]=jtbaddmateriales.getValueAt(i, 2).toString();
            vector[3]=jtbaddmateriales.getValueAt(i, 3).toString();
            vector[4]=jtbaddmateriales.getValueAt(i, 4).toString();

            CreaAPU.modelo_materiales.addRow(vector);
        }
        nueva_tabla();
    }//GEN-LAST:event_btn_añadirActionPerformed

    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
        if( jtbmateriales.getSelectedRow()!=-1){

            try {
                int  elim= jtbmateriales.getSelectedRow();
                DefaultTableModel ELt = (DefaultTableModel)jtbmateriales.getModel();
                ELt.removeRow(elim);
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_btn_quitarActionPerformed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        String[] equipo= {"cod","descripción","costo_hora"};
        //String[] Registro= new String[50];

        String sql = "Select * from equipos where cod like '%"+txtBuscar.getText()+"%'"
        +"or descripción like '%"+txtBuscar.getText()+"%'"
        +"or costo_hora like '%"+txtBuscar.getText()+"%'";

        DefaultTableModel modelo = new DefaultTableModel(null, equipo);
        Connection conn = getConnection();
        //Connection conect = conn.conexion();
        try {
            Statement st = (Statement) conn.createStatement();
            ResultSet rs =st.executeQuery(sql);
            while (rs.next()){
                modelo.addRow(new Object[]{rs.getInt("cod"),rs.getString("descripción"),rs.getDouble("costo_hora")});
            }
            jtbmateriales.setModel(modelo);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        // TODO add your handling code here:
        String nombre = "";
        String unidad = "";
        Double precio = 0.0;
        String cantidad = "0";
        String costo = "0";
        if (jtbmateriales.getSelectedRow() != -1) {

            int col = jtbmateriales.getSelectedRow();
            //code=Integer.parseInt(jtbMateriales.getModel().getValueAt(col, 0).toString()) ;
            nombre = jtbmateriales.getModel().getValueAt(col, 1).toString();
            unidad = jtbmateriales.getModel().getValueAt(col, 2).toString();
            precio = Double.parseDouble(jtbmateriales.getModel().getValueAt(col, 3).toString());
            DefaultTableModel AM = (DefaultTableModel) jtbaddmateriales.getModel();
            // String code2=Integer.toString(code);
            String precio2 = String.valueOf(precio);
            String FilMat[] = {/*code2,*/nombre, unidad, cantidad, precio2, costo};
            AM.addRow(FilMat);
        }
    }//GEN-LAST:event_btn_agregarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtbaddmateriales;
    private javax.swing.JTable jtbmateriales;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
