/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devispro;

import static devispro.Conexion.getConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Crixo
 */
public class Equipos extends javax.swing.JFrame {
    //tabla jtbaddequipo de JFrame Equipos
    DefaultListModel equipo =new DefaultListModel();
    /**
     * Creates new form Equipos
     */
    
    public Equipos() {
        initComponents();
        mostrar();
    }
private void mostrar(){
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = Conexion.getTable("select * from equipos");
        modelo.setColumnIdentifiers(new Object[]{"cod","descripción","costo_hora"});
        try {
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("cod"),rs.getString("descripción"),rs.getDouble("costo_hora")});
            }
            jtbequipo.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

public void nueva_tabla(){
    equipo = new DefaultListModel();
    String[] equipos= {"Descripcion", "costo hora", "Cantidad", "Tarifa", "rendimient", "costo"};
        DefaultTableModel e = new DefaultTableModel(null, equipos);
        jtbaddequipo.setModel(e);                
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnquiList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbequipo = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbaddequipo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("LISTA DE EQUIPOS");

        jButton1.setText("AÑADIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(">");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        btnquiList.setText("<");
        btnquiList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquiListActionPerformed(evt);
            }
        });

        jLabel2.setText("BUSCAR :");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        jtbequipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Descripcion", "costo_hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtbequipo);

        jtbaddequipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "costo hora", "Cantidad", "Tarifa", "rendimiento", "costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtbaddequipo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnquiList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jButton2)
                            .addGap(38, 38, 38)
                            .addComponent(btnquiList))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
         String[] equipo= {"cod","descripción","costo_hora"};
       //String[] Registro= new String[50];
       
       String sql = "Select * from equipos where cod like '%"+txtBuscar.getText()+"%'"
               +"or descripción like '%"+txtBuscar.getText()+"%'"
               +"or costo_hora like '%"+txtBuscar.getText()+"%'";
               
        DefaultTableModel modelo = new DefaultTableModel(null, equipo);
        Connection conn = getConnection();
        //Connection conect = conn.conexion();
        try {
            Statement st = (Statement) conn.createStatement();
            ResultSet rs =st.executeQuery(sql);
            while (rs.next()){
                modelo.addRow(new Object[]{rs.getInt("cod"),rs.getString("descripción"),rs.getDouble("costo_hora")});
            }
            jtbequipo.setModel(modelo);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     String descripcion=""; 
    Double precio=0.0;
        if(jtbequipo.getSelectedRow()!=-1){
            
            int col =jtbequipo.getSelectedRow();
         //code=Integer.parseInt(jtbMateriales.getModel().getValueAt(col, 0).toString()) ;
         descripcion=jtbequipo.getModel().getValueAt(col, 1).toString();
         precio=Double.parseDouble(jtbequipo.getModel().getValueAt(col, 2).toString());
         DefaultTableModel AM = (DefaultTableModel)jtbaddequipo.getModel();
        // String code2=Integer.toString(code);
         String precio2=String.valueOf(precio);
         String FilMat[] = {descripcion,precio2};
         AM.addRow(FilMat);
     }
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnquiListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquiListActionPerformed
         if( jtbaddequipo.getSelectedRow()!=-1){
            
            try {
                int  elim= jtbaddequipo.getSelectedRow();
             DefaultTableModel ELt = (DefaultTableModel)jtbaddequipo.getModel(); 
                ELt.removeRow(elim);
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_btnquiListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<jtbaddequipo.getRowCount(); i++){
            String vector[] = new String[2];
            vector[0]=jtbaddequipo.getValueAt(i, 0).toString();
            vector[1]=jtbaddequipo.getValueAt(i, 1).toString();
            
            CreaAPU.modelo_equipo.addRow(vector);
        }
        nueva_tabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnquiList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtbaddequipo;
    private javax.swing.JTable jtbequipo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
