/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devispro;
import static devispro.Conexion.getConnection;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Crixo
 */
public class Materiales extends javax.swing.JFrame {
    
    DefaultListModel modelo =new DefaultListModel();
    CreaAPU AMat = new CreaAPU();
    //DefaultTableModel modMat= new DefaultTableModel();

    /**
     * Creates new form Materiales
     */
    public Materiales() {
        initComponents();
        mostrar();
    }
    
    private void mostrar(){
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = Conexion.getTable("select * from materiales");
        modelo.setColumnIdentifiers(new Object[]{"cod","nombre","unidad","precio"});
        try {
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("cod"),rs.getString("nombre"),rs.getString("unidad"),rs.getDouble("Precio")});
            }
            jtbMateriales.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    public void nuevaTabla(){
        modelo =new DefaultListModel();
        String[] materiales= {"Descripcion","unidad","P.unitario (b)","Cantidad (A)","Costo (c=a*b)"};
      // String[] Registro= new String[4];
      DefaultTableModel modMat = new DefaultTableModel(null, materiales);
       jtbAAñadir.setModel(modMat);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnaddlista = new javax.swing.JButton();
        btnquitlista = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbMateriales = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbAAñadir = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LISTA DE MATERIALES");

        btnAdd.setText("AÑADIR");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
        });

        jLabel2.setText("BUSCAR :");

        btnaddlista.setText(">");
        btnaddlista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddlistaMouseClicked(evt);
            }
        });

        btnquitlista.setText("<");
        btnquitlista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnquitlistaMouseClicked(evt);
            }
        });

        jtbMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod", "nombre", "unidad", "precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtbMateriales);

        jtbAAñadir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripcion", "Unidad", "p.unitario (B)", "Cantidad (A)", "Costo (C=A*B)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbAAñadir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnaddlista)
                                    .addComponent(btnquitlista))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(11, 11, 11))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnaddlista)
                        .addGap(33, 33, 33)
                        .addComponent(btnquitlista))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addGap(20, 20, 20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
       
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
       String[] materiales= {"cod","nombre","unidad","precio"};
       //String[] Registro= new String[50];
       
       String sql = "Select * from materiales where cod like '%"+txtbuscar.getText()+"%'"
               +"or nombre like '%"+txtbuscar.getText()+"%'"
               +"or unidad like '%"+txtbuscar.getText()+"%'"
               +"or precio like '%"+txtbuscar.getText()+"%'";
        DefaultTableModel modelo = new DefaultTableModel(null, materiales);
        Connection conn = getConnection();
        //Connection conect = conn.conexion();
        try {
            Statement st = (Statement) conn.createStatement();
            ResultSet rs =st.executeQuery(sql);
            while (rs.next()){
                modelo.addRow(new Object[]{rs.getInt("cod"),rs.getString("nombre"),rs.getString("unidad"),rs.getDouble("Precio")});
            }
            jtbMateriales.setModel(modelo);
        } catch (Exception e) {
        }
 
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void btnaddlistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddlistaMouseClicked
     //int code = 0;
     String nombre=""; 
     String unidad="";
     Double precio=0.0;
     String cantidad="0";
     String costo="0";
        if(jtbMateriales.getSelectedRow()!=-1){
            
            int col =jtbMateriales.getSelectedRow();
         //code=Integer.parseInt(jtbMateriales.getModel().getValueAt(col, 0).toString()) ;
         nombre=jtbMateriales.getModel().getValueAt(col, 1).toString();
         unidad=jtbMateriales.getModel().getValueAt(col, 2).toString();
         precio=Double.parseDouble(jtbMateriales.getModel().getValueAt(col, 3).toString());
         DefaultTableModel AM = (DefaultTableModel)jtbAAñadir.getModel();
        // String code2=Integer.toString(code);
         String precio2=String.valueOf(precio);
         String FilMat[] = {/*code2,*/nombre,unidad,precio2,cantidad,costo};
         AM.addRow(FilMat);
     }
    }//GEN-LAST:event_btnaddlistaMouseClicked

    private void btnquitlistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitlistaMouseClicked
       //int eliminar;
        if( jtbAAñadir.getSelectedRow()!=-1){
            
            try {
                int  elim= jtbAAñadir.getSelectedRow();
             DefaultTableModel ELt = (DefaultTableModel)jtbAAñadir.getModel();
                //eliminar = (int)ELt.getValueAt(elim, 0);
                ELt.removeRow(elim);
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_btnquitlistaMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // int code = 0;
     String Descripcion=""; 
     String unidad="";
     Double precio=0.0;
     String cantidad="0";
     String costo="0";
     int numc=jtbAAñadir.getRowCount();
    
     System.out.println(numc);
        try {
            for(int i =0 ;i<numc;i++){     
         Descripcion=jtbMateriales.getModel().getValueAt(i, 1).toString();
         unidad=jtbMateriales.getModel().getValueAt(i, 2).toString();
         precio=Double.parseDouble(jtbMateriales.getModel().getValueAt(i, 3).toString());     
         String precio2=String.valueOf(precio);
         String FilMat[] = {Descripcion,unidad,precio2,cantidad,costo};
       
         CreaAPU.modMat.addRow(FilMat); 
       }
        } catch (Exception e){
            System.out.println(e);
        }
       
       nuevaTabla();
       this.dispose();
       CreaAPU cp = new CreaAPU();
           cp.setVisible(true);
        
    }//GEN-LAST:event_btnAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    private javax.swing.JButton btnaddlista;
    private javax.swing.JButton btnquitlista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtbAAñadir;
    private javax.swing.JTable jtbMateriales;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
