/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devispro;

import static devispro.Conexion.getConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Crixo
 */
public class TRANSPORTE extends javax.swing.JFrame {

    /**
     * Creates new form TRANSPORTE
     */
    public TRANSPORTE() {
        initComponents();
        mostrar();
    }
    private void mostrar(){
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = Conexion.getTable("select * from transporte");
        modelo.setColumnIdentifiers(new Object[]{"cod","descripción","unidad","cantidad","costo"});
        try {
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("cod"),rs.getString("descripción"),rs.getString("unidad"),rs.getInt("cantidad"),rs.getDouble("costo")});
            }
            jtbTransporte.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbus = new javax.swing.JTextField();
        btnAddlista = new javax.swing.JButton();
        btnquitlista = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbTransporte = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbAddTransporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LISTA DE TRANSPORTE");

        jLabel2.setText("BUSCAR :");

        txtbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusActionPerformed(evt);
            }
        });
        txtbus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusKeyPressed(evt);
            }
        });

        btnAddlista.setText(">");
        btnAddlista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddlistaMouseClicked(evt);
            }
        });

        btnquitlista.setText("<");
        btnquitlista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnquitlistaMouseClicked(evt);
            }
        });

        jButton3.setText("Añadir");

        jtbTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cod", "descripcion", "unidad", "cantidad", "costo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtbTransporte);

        jtbAddTransporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "descripcion", "unidad", "cantidad", "costo"
            }
        ));
        jScrollPane4.setViewportView(jtbAddTransporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtbus, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnquitlista)
                                    .addComponent(btnAddlista))))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnAddlista)
                        .addGap(31, 31, 31)
                        .addComponent(btnquitlista))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusActionPerformed

    private void txtbusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusKeyPressed
         String[] equipo= {"cod","descripción","unidad","cantidad","costo"};
       //String[] Registro= new String[50];
       
       String sql = "Select * from transporte where cod like '%"+txtbus.getText()+"%'"
               +"or descripción like '%"+txtbus.getText()+"%'"
               +"or unidad like '%"+txtbus.getText()+"%'"
               +"or cantidad like '%"+txtbus.getText()+"%'"
               +"or costo like '%"+txtbus.getText()+"%'";
               
        DefaultTableModel modelo = new DefaultTableModel(null, equipo);
        Connection conn = getConnection();
        //Connection conect = conn.conexion();
        try {
            Statement st = (Statement) conn.createStatement();
            ResultSet rs =st.executeQuery(sql);
            while (rs.next()){
                 modelo.addRow(new Object[]{rs.getInt("cod"),rs.getString("descripción"),rs.getString("unidad"),rs.getInt("cantidad"),rs.getDouble("costo")});
            }
            jtbTransporte.setModel(modelo);
        } catch (Exception e) {
        }
                                      
    }//GEN-LAST:event_txtbusKeyPressed

    private void btnAddlistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddlistaMouseClicked
     String descripcion=""; 
     String unidad="";
     int cantidad=0;
     Double costo=0.0;
        if(jtbTransporte.getSelectedRow()!=-1){ 
         int col =jtbTransporte.getSelectedRow();
         descripcion=jtbTransporte.getModel().getValueAt(col, 1).toString();
         unidad=jtbTransporte.getModel().getValueAt(col, 2).toString();
         cantidad=Integer.parseInt(jtbTransporte.getModel().getValueAt(col, 3).toString());
         costo=Double.parseDouble(jtbTransporte.getModel().getValueAt(col, 4).toString());
         DefaultTableModel AM = (DefaultTableModel)jtbAddTransporte.getModel();
         String cant=Integer.toString(cantidad);
         String precio2=String.valueOf(costo);
         String FilMat[] = {descripcion,unidad,cant,precio2};
         AM.addRow(FilMat);
     }
    
        
    }//GEN-LAST:event_btnAddlistaMouseClicked

    private void btnquitlistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnquitlistaMouseClicked
           if( jtbAddTransporte.getSelectedRow()!=-1){
            
            try {
                int  elim= jtbAddTransporte.getSelectedRow();
             DefaultTableModel ELt = (DefaultTableModel)jtbAddTransporte.getModel(); 
                ELt.removeRow(elim);
            } catch (Exception e) {
            }
            
        }
    }//GEN-LAST:event_btnquitlistaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRANSPORTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRANSPORTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRANSPORTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRANSPORTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRANSPORTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddlista;
    private javax.swing.JButton btnquitlista;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtbAddTransporte;
    private javax.swing.JTable jtbTransporte;
    private javax.swing.JTextField txtbus;
    // End of variables declaration//GEN-END:variables
}
